Add error handle
JakeRoggenbuck/yfin pull request #61
Opened 2021-12-25 06:20 UTC by JakeRoggenbuck

2021-12-25 07:54 UTC, Camerooooon requested changes
Alright, so I've got some specific feedback for you. Already talked to you about this on discord but just putting it here in words for future reference. Sorry if I'm kinda undermining all of your work but I feel it's important to make a few crucial changes before this PR is beneficial for the project 👍

2021-12-25 07:54 UTC, Camerooooon commented on src/repository.rs
> +pub fn update_repository_cache() -> Result<(), io::Error> {
Ok so, here is why I think it's weird to use io::Error.

io::Error is not formatted for user input. In other words, when we print it out it does not actually tell the user what is wrong. In order to get by this, I converted it to my own generic error::Error which can be printed out to the user. What you've done is replace that generic error with an io error thus making it impossible to tell the user what has gone wrong. Additionally, there is no handle for other types of errors such as requests timing out, the program simply quits because this function can only return errors of type IO error.

2021-12-25 07:54 UTC, Camerooooon commented on src/repository.rs
> +        Err(..) => std::process::exit(1),
Like I said in my previous review std::process::exit(1) doesn't actually tell the user what is going on and completely ignores the error handling provided by reqwest (at this point just unwrap it and panic if there is an error)

2021-12-25 07:54 UTC, Camerooooon commented on src/repository.rs
> +pub fn get_official_repositories() -> Result<HashMap<String, String>, io::Error> {
See original comment on why we should stick with generic error types.

2021-12-25 07:54 UTC, Camerooooon commented on src/repository.rs
>  }
Looks nicer 👍

2021-12-26 20:14 UTC, JakeRoggenbuck commented
Yea, I'll probably close this pr, we can update some error stuff later if we still need it. Thanks for the feedback

2021-12-26 20:14 UTC, closed without merging